### ISSUE TITLE
Turn class components to function components

### ISSUE THREAD

**Issue by LuizHAP** [Kamal-Walia/Emoji-Finder#52]
This project is really good! But can I improve by changing to function components? I'm looking for some issues for Hacktoberfest!

**Comment by LuizHAP** [comment]
@Kamal-Walia

**Comment by Kamal-Walia** [comment]
Sure go ahead

**Comment by Kamal-Walia** [comment]
@LuizHAP

**Comment by LuizHAP** [comment]
Done @Kamal-Walia

**Comment by Kamal-Walia** [comment]
Thanks @LuizHAP, feel free to create more issues to improve the UI or adding denounce when calling gifs API

**Comment by Kamal-Walia** [comment]
Looks good, Will merge once I connect from laptop

**Comment by LuizHAP** [comment]
Waiting @Kamal-Walia . I will create more PRs for this project. Thanks!

**Comment by Kamal-Walia** [comment]
Thanks @LuizHAP, I have merged the pull request
